### ISSUE TITLE
Interface generation from .properties files

### ISSUE THREAD

**Issue by diorcety** [avityuk/ginger#2]
Hi,
Thanks for your project. Great idea.
It will be nice to have the same feature (deprecated now, i don't know why it's a good idea) that gwt to generate interfaces from properties file.
There is such project like https://github.com/ggiamarchi/i18n.generator but it doesn't handle plural like your one (and the generation using template can be limited i think).
Maybe using sun codemodel or the GWT way can be quickly doable.
however some of your features like enums can be tricky to do.
And added to this a maven plugin can be awesome.
Regards,

**Comment by avityuk** [comment]
Thanks for your contributions. I merged pull request with your implementation of interface generator.
