### ISSUE TITLE
core test failures

### ISSUE THREAD

**Issue by diorcety** [avityuk/ginger#3]
Failed tests:   testDateTimeWithFullStyle(com.vityuk.ginger.provider.format.DefaultMessageFormatFactoryTest): expected:<...braio 2013 20.47.23 [PS]T'> but was:<...braio 2013 20.47.23 [CE]T'>
  testTimeWithFullStyle(com.vityuk.ginger.provider.format.DefaultMessageFormatFactoryTest): expected:<'Now is 20.47.23 [PS]T'> but was:<'Now is 20.47.23 [CE]T'>
  testDateTimeWithLongStyle(com.vityuk.ginger.provider.format.DefaultMessageFormatFactoryTest): expected:<... 5, 2013 8:47:23 PM [PS]T'> but was:<... 5, 2013 8:47:23 PM [CE]T'>
  testTimeWithLongStyle(com.vityuk.ginger.provider.format.DefaultMessageFormatFactoryTest): expected:<'Now is 8:47:23 PM [PS]T'> but was:<'Now is 8:47:23 PM [CE]T'>

**Comment by avityuk** [comment]
Fixed.
